/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitestproject_AwesomeTester */

#ifndef _Included_com_example_jnitestproject_AwesomeTester
#define _Included_com_example_jnitestproject_AwesomeTester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitestproject_AwesomeTester
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_jnitestproject_AwesomeTester_nativeCreate
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jnitestproject_AwesomeTester
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_jnitestproject_AwesomeTester_nativeFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_jnitestproject_AwesomeTester
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnitestproject_AwesomeTester_getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_jnitestproject_AwesomeTester
 * Method:    setName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_jnitestproject_AwesomeTester_setName
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_example_jnitestproject_AwesomeTester
 * Method:    getAge
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_jnitestproject_AwesomeTester_getAge
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_jnitestproject_AwesomeTester
 * Method:    setAge
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_example_jnitestproject_AwesomeTester_setAge
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_example_jnitestproject_AwesomeTester
 * Method:    isAwesome
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_jnitestproject_AwesomeTester_isAwesome
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
